computedFields:
  - commune_insee
resources:
  default:
    url: http://opendata.grandnancy.eu/?eID=ics_od_datastoredownload&file=191
    format: shp
    fields:
      _numeroComplet: NUMVOIE
      voie_nom: NOMVOIE
      voie_code: RIVOLI
      long: _geometry.coordinates.0
      lat: _geometry.coordinates.1
