computedFields:
  - codeVoie
beautify: true
resources:
  default:
    url: https://www.data.gouv.fr/s/resources/point-adresse-2/20150605-114705/GPSO_MIG92_Base_PT_Adresse.zip
    format: shp
    fields:
      numero: NUMERO
      suffixe: NUMERO_EXT
      nomVoie: TYPE_VOIE + PREFIXE_VO + NOM_VOIE
      codePostal: CODE_POSTA
      codeCommune: CODE_INSEE
      lon: _geometry.coordinates.0
      lat: _geometry.coordinates.1
