computedFields:
  - voie_nom
resources:
  default:
    url: https://data.seineouest.fr/explore/dataset/base-adresse/download/?format=geojson&timezone=Europe/Berlin
    format: geojson
    fields:
      numero: num
      suffixe: rep
      code_postal: cp
      commune_insee: insee
      lon: _geometry.coordinates.0
      lat: _geometry.coordinates.1
