resources:
  default:
    url: http://geoservices.lorient-agglo.fr/documents/ref_voirie/adresses/shapefile/cc48/la/plaque_adr_ban_aitf.zip
    format: shp
    fields:
      cleInterop: cle_intero
      nomVoie: voie_nom
      numero: numero
      suffixe: suffixe
      lon: _geometry.coordinates.0
      lat: _geometry.coordinates.1
      dateMAJ: date_der_m

