resources:
  default:
    url: https://opendata.arcgis.com/datasets/ce237a8f47bc450d9abd6bfa84a44f74_3.zip
    format: shp
    fields:
      voie_nom: ETIQUETTE
      _numeroComplet: LABEL
      commune_insee: INSEE
      long: _geometry.coordinates.0
      lat: _geometry.coordinates.1
