whiteList:
  - name: Base Adresse Locale de la Métropole de Lyon
    dataset: 5be174928b4c412c5b8cc23f
    url: https://download.data.grandlyon.com/files/grandlyon/localisation/bal/bal_200046977.csv

  - name: Bordeaux Métropole
    importer: bordeaux-metropole
    dataset: 61a025b1557be5ba6399339b
    homepage: https://data.bordeaux-metropole.fr/data.php?layer=FV_ADRESSE_P

  - name: Châlons Agglomération
    importer: chalons-agglomeration
    dataset: 5c14547606e3e7530604ccef
    homepage: http://opendata.chalons-agglo.fr/datasets/ce237a8f47bc450d9abd6bfa84a44f74_3

  - name: Lorient Agglomération
    importer: lorient-agglomeration
    dataset: 5a09aa7288ee383b626c5ea4
    homepage: http://geocatalogue.lorient-agglo.bzh/les-donnees/Cartographie-des-points-adresse-de-Lorient-Agglomeration/12392c369e524cc98cf4c512166c7fed

  - name: Ville de Nanterre
    importer: nanterre-ville
    dataset: 5ad75e1dc751df42a0357f8c
    homepage: https://www.nanterre.fr/1409-les-adresses.htm

  - name: Nice Métropole Côte d’Azur
    importer: nice-metropole
    dataset: 59aea7c9a3a72917d9f3fc92
    homepage: http://opendata.nicecotedazur.org/data/dataset/adresses-sur-le-territoire-de-la-metropole-nca
    comment: La mise à jour automatique n’est pas disponible.

  - name: Ville de Paris
    importer: paris
    dataset: 59590cf0a3a7291dd09c7fd6
    homepage: https://opendata.paris.fr/explore/dataset/adresse_paris/

  - name: Saint-Brieuc Armor Agglomération
    url: https://datarmor.cotesdarmor.fr/data-unpaginated/dataserver/cg22/data/200069409_base_adresse_locale?&$inlinecount=allpages&$format=csv
    slug: saint-brieuc-armor-agglomeration
    organization: 5acb2f2088ee3813a476714d
    homepage: https://datarmor.cotesdarmor.fr/data-presentation-ux/#/cg22/datasets/200069409_base_adresse_locale/views/desc
    odbl: true
    # Non référencé sur data.gouv.fr à ce jour

  - name: Lamballe Terre & Mer
    url: https://datarmor.cotesdarmor.fr/data-unpaginated/dataserver/cg22/data/200069391_base_adresse_locale?&$inlinecount=allpages&$format=csv
    slug: lamballe-terre-et-mer
    organization: 6070bad3ca2307e2a74e6150
    homepage: https://datarmor.cotesdarmor.fr/data-presentation-ux/#/cg22/datasets/200069391_base_adresse_locale/views/desc
    # Non référencé sur data.gouv.fr à ce jour

  - name: Grenoble
    dataset: 5af03721b595081c1c80a8ad
    importer: grenoble

  - name: Metz Métropole
    dataset: 542ab42f88ee382b8f22e2e4
    importer: metz-metropole

  - name: La Rochelle
    organization: 5821930b88ee386862c65bb3
    slug: la-rochelle
    importer: la-rochelle

  - name: Bassussarry
    importer: bassussarry
    slug: bassussarry

  - name: BAL du Grand Poitiers
    importer: grand-poitiers
    dataset: 5e3007a28b4c416184143179

  - name: Référentiel Adresses du Pays Compiégnois
    url: http://geo.compiegnois.fr/documents/referentiel/adresse/bal/payscompiegnois_bal.csv
    dataset: 5bf2b569634f410e3285adda
    # By-pass de geo.data.gouv.fr (cache non pertinent)

  - name: Ville de Marseille
    url: https://adresse.data.gouv.fr/data/sources-locales/marseille/bal.csv
    slug: marseille
    # Non référencé sur data.gouv.fr

  - name: Adresses d’Innimond
    importer: innimond
    dataset: 5f22ad7bd878f3976265af48

  # Dépublication temporaire le temps d'améliorer la qualité des données
  # - name: Base Adresse Locale de Durance-Luberon-Verdon Agglomération
  #   importer: dlva
  #   dataset: 5f8e9b24e5cf95adcc819c48

blackList:
  - name: Sixt-sur-Aff
    dataset: 5d1b155b634f41553150048e
    # Non valide

  - name: Pirae (Polynésie française)
    dataset: 5d5f25846f444112e0dfc2cd
    # Non supporté à ce stade

  - name: Base Adresse Locale sur le territoire de la Métropole NCA
    dataset: 5c2459b206e3e7551204ccef
    # Alternative moins complète au format BAL, et invalide

  - name: dlva
    dataset: 5f8e9b24e5cf95adcc819c48

  - name: Points Adresse de Lannion-Trégor Communauté
    dataset: 59c3a54388ee38019cc19cbc
    # Ancien jeu de données non retiré de data.gouv.fr

  - dataset: 5e322303dee7e71547f5c8ec
    # Doublon moissonnage ODS Pays de la Loire

  - dataset: 5d72f45106e3e76febd78afd
  - dataset: 60a3c6c477ced898a49a7035
  - dataset: 5d72f45106e3e76fa1d78afd
  - dataset: 604f15cce08ecc08b88f5617
  - dataset: 612904755f59b6818346ea4e
  - dataset: 6129047508917df8f846ea4f
