whiteList:
  - name: Châlons Agglomération
    converter: chalons-agglomeration
    dataset: 5c14547606e3e7530604ccef
    homepage: http://opendata.chalons-agglo.fr/datasets/ce237a8f47bc450d9abd6bfa84a44f74_3

  - name: Ville de Paris
    converter: paris
    dataset: 59590cf0a3a7291dd09c7fd6
    homepage: https://opendata.paris.fr/explore/dataset/adresse_paris/

  - name: Lamballe Terre & Mer
    url: https://datarmor.cotesdarmor.fr/data-unpaginated/dataserver/cg22/data/200069391_base_adresse_locale?&$inlinecount=allpages&$format=csv
    slug: lamballe-terre-et-mer
    organization: 6070bad3ca2307e2a74e6150
    homepage: https://datarmor.cotesdarmor.fr/data-presentation-ux/#/cg22/datasets/200069391_base_adresse_locale/views/desc
    # Non référencé sur data.gouv.fr à ce jour

  - name: Grenoble
    dataset: 5af03721b595081c1c80a8ad
    converter: grenoble

  - name: La Rochelle
    organization: 5821930b88ee386862c65bb3
    slug: la-rochelle
    converter: la-rochelle

  - name: BAL du Grand Poitiers
    converter: grand-poitiers
    dataset: 5e3007a28b4c416184143179

  - name: Référentiel Adresses du Pays Compiégnois
    url: http://geo.compiegnois.fr/documents/referentiel/adresse/bal/payscompiegnois_bal.csv
    dataset: 5bf2b569634f410e3285adda
    # By-pass de geo.data.gouv.fr (cache non pertinent)

  - name: Ville de Marseille
    url: https://adresse.data.gouv.fr/data/sources-locales/marseille/bal.csv
    slug: marseille
    # Non référencé sur data.gouv.fr

  - name: Adresses de Saint-Denis (La Réunion)
    converter: saint-denis-reunion
    dataset: 5d2e6b939ce2e7643a90b663

  - name: Adresses de Nouméa
    converter: noumea
    slug: noumea

blackList:
  - name: Sixt-sur-Aff
    dataset: 5d1b155b634f41553150048e
    # Non valide

  - name: Pirae (Polynésie française)
    dataset: 5d5f25846f444112e0dfc2cd
    # Non supporté à ce stade

  - name: dlva
    dataset: 5f8e9b24e5cf95adcc819c48

  - name: Points Adresse de Lannion-Trégor Communauté
    dataset: 59c3a54388ee38019cc19cbc
    # Ancien jeu de données non retiré de data.gouv.fr

  - dataset: 5e322303dee7e71547f5c8ec
    # Doublon moissonnage ODS Pays de la Loire

  - dataset: 5d72f45106e3e76febd78afd
  - dataset: 60a3c6c477ced898a49a7035
  - dataset: 5d72f45106e3e76fa1d78afd
  - dataset: 612904755f59b6818346ea4e
  - dataset: 6129047508917df8f846ea4f
