whiteList:
  - name: Base adresse locale - Angers
    slug: angers
    url: https://data.angers.fr/explore/dataset/base-adresse-locale-angers/download/?format=csv&timezone=Europe/Berlin&use_labels_for_header=true
    organization: 538346d6a3a72906c7ec5c36
    homepage: https://data.angers.fr/explore/dataset/base-adresse-locale-angers/

  - name: Bordeaux Métropole
    importer: bordeaux-metropole
    dataset: 5a02bf6188ee38130d1057c9
    homepage: https://data.bordeaux-metropole.fr/data.php?layer=FV_ADRESSE_P

  - name: Châlons Agglomération
    importer: chalons-agglomeration
    dataset: 5c14547606e3e7530604ccef
    homepage: http://opendata.chalons-agglo.fr/datasets/ce237a8f47bc450d9abd6bfa84a44f74_3

  - name: Colmar Agglomération
    importer: colmar-agglomeration
    slug: colmar-agglomeration
    homepage: https://www.agglo-colmar.fr/geo

  - name: Grand Nancy
    importer: grand-nancy
    slug: grand-nancy
    organization: 534fff65a3a7292c64a77d73
    homepage: http://opendata.grandnancy.eu/jeux-de-donnees/detail-dune-fiche-de-donnees/?tx_icsoddatastore_pi1%5Buid%5D=82&tx_icsoddatastore_pi1%5BreturnID%5D=447

  - name: Grand Paris Seine Ouest
    importer: grand-paris-seine-ouest
    dataset: 55716fe9c751df588de5726a

  - name: Lille Métropole
    importer: lille-metropole
    dataset: 58b69b21a3a7295a7d8251b5
    homepage: https://opendata.lillemetropole.fr/explore/dataset/seuils_adresses_mel/

  - name: Lorient Agglomération
    importer: lorient-agglomeration
    dataset: 5a09aa7288ee383b626c5ea4
    homepage: http://geocatalogue.lorient-agglo.bzh/les-donnees/Cartographie-des-points-adresse-de-Lorient-Agglomeration/12392c369e524cc98cf4c512166c7fed

  - name: Ville de Montpellier
    importer: montpellier
    slug: montpellier
    organization: 5847cb5cc751df5d58c0bb7e
    homepage: http://data.montpellier3m.fr/dataset/point-adresse-de-montpellier

  - name: Mulhouse Alsace Agglomération
    importer: mulhouse-alsace-agglomeration
    dataset: 5be560f59ce2e72d66831010
    homepage: https://data.mulhouse-alsace.fr/explore/dataset/m2a_base-adresse/information/

  - name: Ville de Nanterre
    importer: nanterre-ville
    dataset: 5ad75e1dc751df42a0357f8c
    homepage: https://www.nanterre.fr/1409-les-adresses.htm

  - name: Nantes Métropole
    importer: nantes-metropole
    dataset: 5b4ee8c8b595087918d496d2
    homepage: https://data.nantesmetropole.fr/explore/dataset/244400404_adresses-postales-nantes-metropole/information/

  - name: Nice Métropole Côte d’Azur
    importer: nice-metropole
    dataset: 59aea7c9a3a72917d9f3fc92
    homepage: http://opendata.nicecotedazur.org/data/dataset/adresses-sur-le-territoire-de-la-metropole-nca
    comment: La mise à jour automatique n’est pas disponible.

  - name: Ville de Paris
    importer: paris
    dataset: 59590cf0a3a7291dd09c7fd6
    homepage: https://opendata.paris.fr/explore/dataset/adresse_paris/

  - name: Quimper Bretagne Occidentale
    importer: quimper-bretagne-occidentale
    dataset: 5b5aea25c751df35616a7420
    homepage: https://geobretagne.fr/geonetwork/srv/fre/catalog.search#/metadata/4a9179ee-1cad-49f1-9746-e2e377a8fc95

  - name: Pays de Saint-Brieuc
    url: http://datarmor.cotesdarmor.fr/data-unpaginated/dataserver/cg22/data/2200542_base_adresse_locale?&$inlinecount=allpages&$format=csv
    slug: pays-saint-brieuc
    organization: 5acb2f2088ee3813a476714d
    homepage: http://datarmor.cotesdarmor.fr/data-presentation-ux/#/cg22/datasets/2200542_base_adresse_locale/views/desc
    odbl: true

  - name: Antibes - Juan-les-Pins
    url: http://www.antibes-juanlespins.com/OpenData/Antibes_base_adresses_locales.csv
    slug: antibes-juan-les-pins
    organization: 566594f388ee38738640355c
    homepage: http://www.antibes-juanlespins.com/administration/open-data/administration/base-adresses-locales-bal

  - name: CARENE
    url: https://data.agglo-carene.fr/explore/dataset/244400644_bal/download/?format=csv&timezone=Europe/Berlin&use_labels_for_header=true
    slug: carene
    organization: 5733009988ee3843a3d1b934
    homepage: https://data.agglo-carene.fr/explore/dataset/244400644_bal/table/

  - name: Loire Forez Agglomération
    dataset: 5bed86a78b4c41546f05613c
    # Liste blanche pour réécriture du titre

  - name: Le Plessis-Trévise
    dataset: 5bbcc694634f411d5e251ca6
    # Liste blanche pour réécriture du titre

  - name: Toulouse Métropole
    dataset: 5bc6d04e9ce2e726fa422d3e
    # Liste blanche pour réécriture du titre

  # Commune d'Anglet
  - dataset: 5cac5d4c9ce2e71425bc8896

  - name: Grenoble
    dataset: 5af03721b595081c1c80a8ad
    importer: grenoble

  - name: Communauté de l’Agglomération Havraise (CODAH)
    dataset: 5a3100e188ee385a3eeb4aa0
    importer: le-havre-agglomeration

  - name: Limoges
    dataset: 54b52ca6c751df7556ae2614
    importer: limoges

  - name: Metz Métropole
    dataset: 542ab42f88ee382b8f22e2e4
    importer: metz-metropole

  - name: La Rochelle
    dataset: 5bb6b4749ce2e701e12456a5
    importer: la-rochelle

  - name: Arles-Crau-Camargue-Montagnette
    homepage: https://trouver.datasud.fr/dataset/base-locale-dadresses-accm
    organization: 534fff55a3a7292c64a77cde
    importer: accm
    slug: accm

  - name: Bassussarry
    importer: bassussarry
    slug: bassussarry

  - name: Dordogne
    importer: dordogne
    dataset: 5c4b12068b4c41486162c728

  - name: Base Adresse Locale de Digne-les-Bains
    url: https://trouver.datasud.fr/dataset/e198ead6-047b-4608-b1d7-7d488a773193/resource/a7a05846-037e-42cc-8f66-0197c64f4f5c/download/digne-bal-2018.csv
    homepage: https://trouver.datasud.fr/dataset/base-adresse-locale-de-digne-les-bains
    slug: digne-les-bains

  - name: Grand Poitiers
    url: https://data.grandpoitiers.fr/explore/dataset/referentiel-geographique-adresses-ban-gpcu-grand-poitiers-donnees-de-reference/download/?format=csv&timezone=Europe/Berlin&use_labels_for_header=true
    organization: 54da1f52c751df59f7467389
    slug: grand-poitiers
    homepage: https://data.grandpoitiers.fr/explore/dataset/referentiel-geographique-adresses-ban-gpcu-grand-poitiers-donnees-de-reference/information/

  - name: Référentiel Adresses du Pays Compiégnois
    url: http://geo.compiegnois.fr/documents/referentiel/adresse/bal/payscompiegnois_bal.csv
    dataset: 5bf2b569634f410e3285adda

  - name: Ville de Marseille
    url: https://adresse.data.gouv.fr/data/sources-locales/marseille/bal.csv
    slug: marseille

  - name: BAL de la Communauté d'Agglomération du Puy-en-Velay
    url: https://opendata.agglo-lepuyenvelay.fr/geoadressage/opendata/adresses/bal
    organization: 5cd531978b4c41605df23b89
    slug: agglo-lepuyenvelay

  - name: BAL du Grand Belfort
    url: http://belfort-cab.opendata.arcgis.com/datasets/1475ecd2d6fb4f83bb8cd78b17b6dd10_0.csv
    dataset: 5d4a150b9ce2e72797fae2e2

blackList:
  - name: BAL Cap Atlantique / Nantes Métropole
    dataset: 5bc53abf06e3e76f9a88f2c4
    # Doublon lié au moissonnage OpenDataSoft

  - name: BAL Cap Atlantique / Pays de la Loire
    dataset: 5bd9067a06e3e739998c0ebb
    # Doublon lié au moissonnage OpenDataSoft

  - name: Bayonne
    dataset: 5b0c070dc751df3203606268
    # Fichier expérimental qui n'est plus mis à jour mais non supprimé à la source

  - name: Ville de Lorient - Rattachement des secteurs
    dataset: 5c70a7f99ce2e760225908e1
    # Non pertinent

  - name: Ville de Lorient - Rattachement des îlots IRIS
    dataset: 5c76daa09ce2e727161da1ae
    # Non pertinent

  - name: Ville de Lorient - Rattachement des établissements scolaires
    dataset: 5c70a7f706e3e755537bb84b
    # Non pertinent

  - name: Ville de Lorient - Rattachement des bureaux de vote
    dataset: 5c70a7f806e3e755537bb84c
    # Non pertinent

  - name: Ville de Nancy
    dataset: 5ce6b0ea8b4c414941e1d2d5
    # Inversion latitude et longitude, licence ODbL alors que les données Grand Nancy sont disponibles en LO

  - name: Sixt-sur-Aff
    dataset: 5d1b155b634f41553150048e
    # Non valide
