computedFields:
  - nomVoie
  - codeCommune
resources:
  default:
    url: http://entrepot.metropolegrenoble.fr/opendata/38185-GRE/PlanDeVille/json/PLANDEVILLE_ADRES_VDG_EPSG4326.json
    format: geojson
    fields:
      codePostal: ADRES_CODEPOST
      numeroComplet: ADRES_LIBEL
      codeVoie: VOIR_FANTOIR
      lon: _geometry.coordinates.0
      lat: _geometry.coordinates.1
