resources:
  default:
    url: https://adresse.data.gouv.fr/data/sources-locales/64100-bassussarry/referentiel_adresse__64100_2019.zip
    format: shp
    fields:
      numero: numero_sel
      voie_nom: libelle_vo
      voie_code: rivoli
      commune_insee: code_insee
      long: _geometry.coordinates.0
      lat: _geometry.coordinates.1
