join:
  - resource: indicesRepetition
    key: _idSuffixe
  - resource: troncons
    key: _idTroncon
  - resource: voies
    key: _idVoie
computedFields:
  - commune_insee
resources:
  default:
    url: https://opendata.agglo-larochelle.fr/api/records/2.0/downloadfile/format=geojson&resource_id=f55cc411-646c-4c80-bc34-013cbf7e5077
    format: geojson
    fields:
      numero: numero_valeur
      _idSuffixe: numero_indice_repetition_id
      _idTroncon: numero_id_troncon
      long: _geometry.coordinates.0
      lat: _geometry.coordinates.1
  indicesRepetition:
    url: https://opendata.agglo-larochelle.fr/api/records/2.0/downloadfile/format=csv&resource_id=bd7c9491-14ab-48d5-9baa-a65bf2309ca6&use_labels_for_header=true&user_defined_fields=true
    format: csv
    fields:
      _idSuffixe: ind_id
      suffixe: ind_libelle
  troncons:
    url: https://opendata.agglo-larochelle.fr/api/records/2.0/downloadfile/format=csv&resource_id=7e04daba-2f0e-4284-a063-6d3e7e9896db&use_labels_for_header=true&user_defined_fields=true
    format: csv
    fields:
      _idTroncon: troncon_id
      _idVoie: troncon_voie_id
  voies:
    url: https://opendata.agglo-larochelle.fr/api/records/2.0/downloadfile/format=csv&resource_id=1c8f1ff3-c96a-4e41-bc7e-fce4e6a364c8&use_labels_for_header=true&user_defined_fields=true
    format: csv
    fields:
      _idVoie: voie_id
      voie_nom: voie_libel
      voie_code: voie_fanto
