resources:
  default:
    url: http://webcarto.agglo-accm.fr/ressources/donnees_ouvertes/adresse.adr_accm_adresse.zip
    format: shp
    encoding: utf-8
    fields:
      numero: NUM_VOI
      suffixe: SUF_VOI
      nomVoie: NOM_REEL
      codeVoie: RIVOLI
      codeCommune: CODCOMM
      codePostal: CODE_POSTA
      dateMAJ: DATE_MAJ
      lon: _geometry.coordinates.0
      lat: _geometry.coordinates.1
