computedFields:
  - codeVoie
resources:
  default:
    url: https://data.bordeaux-metropole.fr/files.php?gid=866&format=2
    format: shp
    fields:
      numero: NUMERO
      suffixe: REP
      nomVoie: NOM_VOIE
      codeCommune: CINSEE
      codePostal: CPOSTAL
      lon: _geometry.coordinates.0
      lat: _geometry.coordinates.1



