computedFields:
  - codeVoie
  - codeCommune
resources:
  default:
    url: https://opendata.bordeaux-metropole.fr/explore/dataset/fv_adresse_p/download/?format=geojson&timezone=Europe/Berlin&lang=fr
    format: geojson
    fields:
      numero: numero
      suffixe: rep
      nomVoie: nom_voie
      codePostal: cpostal
      lon: _geometry.coordinates.0
      lat: _geometry.coordinates.1



