computedFields:
  - nomVoie
  - codeVoie
resources:
  default:
    url: https://opendata.lillemetropole.fr/explore/dataset/seuils_adresses_mel/download/?format=geojson&timezone=Europe/Berlin
    format: geojson
    fields:
      numero: numero
      suffixe: suffixe
      codeCommune: comm_id
      codePostal: cpostal
      lon: _geometry.coordinates.0
      lat: _geometry.coordinates.1
