computedFields:
  - commune_insee
  - voie_code
  - voie_nom
  - date_der_maj
resources:
  default:
    url: https://geobretagne.fr/geoserver/qbo/ows?service=wfs&version=1.0.0&request=getfeature&typename=adresse_qbo&outputformat=shape-zip
    format: shp
    fields:
      _numeroComplet: ADR_TEXT
      long: _geometry.coordinates.0
      lat: _geometry.coordinates.1
