resources:
  default:
    url: https://data.grandpoitiers.fr/explore/dataset/referentiel-geographique-adresses-ban-gpcu-grand-poitiers-donnees-de-reference/download/?format=geojson&timezone=Europe/Berlin
    format: geojson
    fields:
      cle_interop: cle_interop
      commune_insee: code_insee
      voie_nom: voie_nom
      numero: numero
      suffixe: suffixe
      long: _geometry.coordinates.0
      lat: _geometry.coordinates.1
      date_der_maj: date_der_maj
      source: source
      position: position

