computedFields:
  - codeCommune
resources:
  default:
    url: https://data.strasbourg.eu/explore/dataset/referentiel-adresse/download?format=geojson&timezone=Europe/Berlin&use_labels_for_header=true
    format: geojson
    fields:
      nomVoie: nom_rue
      numeroComplet: numero
      lon: _geometry.coordinates.0
      lat: _geometry.coordinates.1
