
computedFields:
  - codeCommune
resources:
  default:
    url: https://www.data.gouv.fr/fr/datasets/r/e3353d4e-6c09-4561-bf6c-1805c86a7d29
    format: sheet
    fields:
      numero: Num
      nomVoie: Rue
      lon: longitude
      lat: latitude
