resources:
  default:
    url: https://data.mulhouse-alsace.fr/explore/dataset/m2a_base-adresse/download/?format=geojson&timezone=Europe/Berlin
    format: geojson
    fields:
      numero: numero
      suffixe: suffixe
      nomVoie: libelle_ba
      codeVoie: code_rivol
      codePostal: code_post
      codeCommune: code_insee
      lon: _geometry.coordinates.0
      lat: _geometry.coordinates.1
