computedFields:
  - nomVoie
  - codeCommune
resources:
  default:
    url: https://data.nantesmetropole.fr/explore/dataset/244400404_adresses-postales-nantes-metropole/download/?format=geojson&timezone=Europe/Berlin
    format: geojson
    fields:
      codePostal: code_postal
      numeroComplet: numero
      codeVoie: rivoli
      iris: iris2008
      lon: _geometry.coordinates.0
      lat: _geometry.coordinates.1
