computedFields:
  - voie_nom
  - voie_code
resources:
  default:
    url: https://opendata.lillemetropole.fr/explore/dataset/seuils_adresses_mel/download/?format=geojson&timezone=Europe/Berlin
    format: geojson
    fields:
      numero: numero
      suffixe: suffixe
      commune_insee: comm_id
      code_postal: cpostal
      long: _geometry.coordinates.0
      lat: _geometry.coordinates.1
