join:
  - resource: voies
    key: _idVoie
resources:
  default:
    url: https://www.data.gouv.fr/fr/datasets/r/1cbb1e3a-b915-4103-95ad-6a9feb3c8187
    format: shp
    fromEPSG: 3946
    fields:
      _numeroComplet: NUMERO
      code_postal: CODE_POSTA
      date_der_maj: DATE_MAJ
      _idVoie: ID_VOIE
      long: _geometry.coordinates.0
      lat: _geometry.coordinates.1
  voies:
    url: https://www.data.gouv.fr/fr/datasets/r/8389185c-8e81-42ad-8565-9d78bb79a120
    format: sheet
    fields:
      _idVoie: ID_VOIE
      voie_nom: TYPE_VOIE_ACC + NOM_ACC
      voie_code: RIVOLI_DGI
      commune_insee: CODCOMM
