resources:
  default:
    url: https://www.agglo-colmar.fr/data/geo/OpenData/FR-246800726-678/FR-246800726-678.zip
    archivePath: FR-246800726-678.json
    format: geojson
    fromEPSG: 3948
    fields:
      nomVoie: voie
      numeroComplet: numero
      codeCommune: com_insee_num
      codeVoie: rivoli
      lon: _geometry.coordinates.0
      lat: _geometry.coordinates.1
