resources:
  default:
    url: https://www.agglo-colmar.fr/data/geo/OpenData/FR-246800726-0678/FR-246800726-0678.zip
    archivePath: FR-246800726-0678.json
    format: geojson
    fromEPSG: 3948
    fields:
      voie_nom: voie
      _numeroComplet: numero
      commune_insee: com_insee_num
      voie_code: rivoli
      long: _geometry.coordinates.0
      lat: _geometry.coordinates.1
