resources:
  default:
    url: https://www.data.gouv.fr/fr/datasets/r/cf19c81f-b024-42c5-98be-d65b5730ddc0
    format: csv
    fields:
      nomVoie: nom_voie
      numero: numero
      suffixe: rep
      codeCommune: insee
      lon: lon
      lat: lat
