join:
  - resource: voies
    key: _idVoie
computedFields:
  - codeCommune
resources:
  default:
    url: https://opendata.paris.fr/explore/dataset/adresse_paris/download/?format=geojson&timezone=Europe/Berlin
    format: geojson
    fields:
      numeroComplet: l_nvoie
      _idVoie: n_sq_vo
      lon: _geometry.coordinates.0
      lat: _geometry.coordinates.1
  voies:
    url: https://opendata.paris.fr/explore/dataset/voie/download/?format=geojson&timezone=Europe/Berlin
    format: geojson
    fields:
      _idVoie: n_sq_vo
      nomVoie: l_longmin
