join:
  - resource: voies
    key: _idVoie
computedFields:
  - commune_insee
resources:
  default:
    url: https://opendata.paris.fr/explore/dataset/adresse_paris/download/?format=geojson&timezone=Europe/Berlin
    format: geojson
    fields:
      _numeroComplet: l_nvoie
      _idVoie: n_sq_vo
      long: _geometry.coordinates.0
      lat: _geometry.coordinates.1
  voies:
    url: https://opendata.paris.fr/explore/dataset/voie/download/?format=geojson&timezone=Europe/Berlin
    format: geojson
    fields:
      _idVoie: n_sq_vo
      voie_nom: l_longmin
