computedFields:
  - commune_insee
resources:
  default:
    url: http://data.montpellier3m.fr/sites/default/files/ressources/MMM_MTP_PointAdresse.json
    format: geojson
    fields:
      voie_nom: liboff
      voie_code: rivoli
      numero: num_voi
      suffixe: suf_voi
      long: _geometry.coordinates.0
      lat: _geometry.coordinates.1
