computedFields:
  - codeCommune
resources:
  default:
    url: http://data.montpellier3m.fr/sites/default/files/ressources/MMM_MTP_PointAdresse.json
    format: geojson
    fields:
      nomVoie: liboff
      codeVoie: rivoli
      numero: num_voi
      suffixe: suf_voi
      lon: _geometry.coordinates.0
      lat: _geometry.coordinates.1
