resources:
  default:
    url: https://static.data.gouv.fr/resources/base-adresse-locale-de-la-dordogne/20190125-155010/20190125-adresses-atd24.csv
    format: csv
    fields:
      codeCommune: code_insee
      numero: numero
      suffixe: suffixe
      nomVoie: voie_nom
      position: position
      source: source
      dateMAJ: date_der_maj
      lon: long
      lat: lat
