join:
  - resource: voies
    key: _idVoie
resources:
  default:
    url: https://maps.metzmetropole.fr/ows?service=WFS&version=2.0.0&request=GetFeature&typeName=public:fdp_voi_nume&srsName=EPSG:4326&outputFormat=json
    format: geojson
    fields:
      _numeroComplet: lib
      _idVoie: _voie
      commune_insee: _commid
      long: _geometry.coordinates.0
      lat: _geometry.coordinates.1
  voies:
    url: https://maps.metzmetropole.fr/ows?service=WFS&version=2.0.0&request=GetFeature&typeName=public:fdp_voi_voie&srsName=EPSG:4326&outputFormat=json
    format: geojson
    fields:
      _idVoie: id
      voie_nom: libcomplet
      voie_code: riv
