resources:
  default:
    url: http://opendata.nicecotedazur.org/data/storage/f/2018-03-30T08%3A29%3A28.853Z/ig-base-adresses.geojson
    format: geojson
    fields:
      numero: SIGNCA_IG_BASE_ADRESSES_NUM
      suffixe: SIGNCA_IG_BASE_ADRESSES_IND_REP
      nomVoie: SIGNCA_IG_AXEVOIE_NOM_MINU
      codeCommune: SIGNCA_IG_BASE_ADRESSES_CODE_INSEE
      lon: _geometry.coordinates.0
      lat: _geometry.coordinates.1
